//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.SeasonPlayerPositionStats = new HashSet<SeasonPlayerPositionStat>();
            this.SeasonTeamPlayers = new HashSet<SeasonTeamPlayer>();
            this.Seasons = new HashSet<Season>();
        }
    
        public System.Guid PlayerGUID { get; set; }
        public string PlayerName { get; set; }
        public byte[] PlayerImage { get; set; }
    
        public virtual ICollection<SeasonPlayerPositionStat> SeasonPlayerPositionStats { get; set; }
        public virtual ICollection<SeasonTeamPlayer> SeasonTeamPlayers { get; set; }
        public virtual PlayerPosition PlayerPosition { get; set; }
        public virtual ICollection<Season> Seasons { get; set; }
    }
}
