//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public Season()
        {
            this.SeasonTeamStadiums = new HashSet<SeasonTeamStadium>();
            this.SeasonTeams = new HashSet<SeasonTeam>();
            this.Players = new HashSet<Player>();
            this.Stadia = new HashSet<Stadium>();
        }
    
        public int SeasonID { get; set; }
        public string SeasonName { get; set; }
        public System.DateTime DraftDate { get; set; }
        public int StartPoints { get; set; }
        public Nullable<int> MinBid { get; set; }
    
        public virtual ICollection<SeasonTeamStadium> SeasonTeamStadiums { get; set; }
        public virtual ICollection<SeasonTeam> SeasonTeams { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<Stadium> Stadia { get; set; }
    }
}
