//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.SeasonTeams = new HashSet<SeasonTeam>();
            this.SeasonTeamStadiums = new HashSet<SeasonTeamStadium>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.Guid> OwnerUserID { get; set; }
        public string OwnerEmail { get; set; }
        public byte[] TeamImage { get; set; }
    
        public virtual ICollection<SeasonTeam> SeasonTeams { get; set; }
        public virtual ICollection<SeasonTeamStadium> SeasonTeamStadiums { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
