//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeStatu
    {
        public TradeStatu()
        {
            this.Trades = new HashSet<Trade>();
            this.TradeTeams = new HashSet<TradeTeam>();
        }
    
        public int TradeStatusID { get; set; }
        public string TradeStatusDesc { get; set; }
    
        public virtual ICollection<Trade> Trades { get; set; }
        public virtual ICollection<TradeTeam> TradeTeams { get; set; }
    }
}
