//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PlayerPositions
    {
        public System.Guid PlayerGUID { get; set; }
        public string PlayerName { get; set; }
        public byte[] PlayerImage { get; set; }
        public int PrimaryPositionID { get; set; }
        public Nullable<int> SecondaryPostiionID { get; set; }
        public string PrimPosName { get; set; }
        public string PrimPosNameLong { get; set; }
        public string SecPosName { get; set; }
        public string SecPosNameLong { get; set; }
    }
}
